server:
  port: 9000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fullformat12/config-repo-demo
          default-label: main
  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: busrefresh

