spring:
  application:
    name: billing-service
  cloud:
    stream:
      bindings:
        orderCompleted-in-0:
          destination: ORDER_PROCESSING_COMPLETED
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
